### ISSUE TITLE
Can't login to webmaker account through goggles

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/login.webmaker.org#314]
Seems spotty -- happens for some accounts, but not others.

1. Go to goggles.mofostaging.net
2. Try to sign in.
3. :(

```
POST http://goggles.mofostaging.net/auth/v2/uid-exists 403 (Forbidden)
POST http://goggles.mofostaging.net/verify 403 (Forbidden)
webmakerLogin.js:1957 Uncaught TypeError: Uncaught, unspecified "error" event.
```

**Comment by jbuck** [comment]
If only I looked at this better... The problem was that it was possible to connect to goggles staging using HTTP. Since our cookies are marked Secure, you could never save your CSRF token and thus, never sign in.

**Comment by secretrobotron** [comment]
:+1: you da best, @jbuck
