### ISSUE TITLE
I don't understand this UI

### ISSUE THREAD

**Issue by davidascher** [mozilla/login.webmaker.org#319]
![screenshot 2015-02-17 14 12 19](https://cloud.githubusercontent.com/assets/51278/6238578/293e59a0-b6b1-11e4-8310-fe4e4f482bd0.png)

Specifically the repetition of US-English

/cc @alicoding

**Comment by davidascher** [comment]
Also the weird grey dot over the second "US"

**Comment by alicoding** [comment]
I think we've changed the drop down UI to nativeName - englishName which is unnecessary at all here

```
    'en-US': {
      nativeName: "English (US)",
      englishName: "English (US)"
    },
```

I think we should just leave it as `nativeName` so it will be `English (US)` for English and `ภาษาไทย` for Thai
