### ISSUE TITLE
Login appears to be broken on events.wmo production

### ISSUE THREAD

**Issue by gesa** [mozilla/login.webmaker.org#328]
*Browser:* ALL
*Screenshot:* ![ng0ds](https://cloud.githubusercontent.com/assets/782056/6884106/1e86c190-d5a2-11e4-8a8d-37f97c77ba23.png)

**Repro Steps:**
1. Click “Login” on events.webmaker.org
2. Type email address into field
3. Click “Sign In”

**Expected:** key is emailed to me
**Actual:** no response. clicking “Sign In” appears to have no impact on the page

**Comment by gesa** [comment]
(I should note I have no problem signing in on staging.)

**Comment by jbuck** [comment]
@gesa This was because of an incorrect configuration on the events front-end, which is now fixed. Hooray!
