### ISSUE TITLE
Sign up broken on events.wmo

### ISSUE THREAD

**Issue by gesa** [mozilla/login.webmaker.org#329]
*Browser:* ALL
*Screenshot:* 
![g6x4c](https://cloud.githubusercontent.com/assets/782056/6884110/55249312-d5a2-11e4-9288-2aef61c75762.png)

**Repro Steps:**
1. Click “Join Webmaker”
2. enter email
3. click “Join”

**Expected:** Email recorded, time to set a url name
**Actual:** The modal to set url name appears, but with the error `An unknown error occurred on the server. Try your request again. If the problem persists, get help.`

(Can't reproduce on staging)

**Comment by jbuck** [comment]
@gesa This was because of an incorrect configuration on the events front-end, which is now fixed. Hooray!
