### ISSUE TITLE
Unable to delete account

### ISSUE THREAD

**Issue by amirad** [mozilla/login.webmaker.org#344]
User emailed saying hyperlink in "Settings" to delete account is not working. I just tested it with my own account and also cannot delete it.

**Comment by jbuck** [comment]
@amirad Can you confirm that the hyperlink that you visited is https://login.webmaker.org/account or https://login.mofostaging.net/account ?

I was able to sign in to my account and delete my account successfully. Do you see any error messages when you attempt to delete your account?

**Comment by amirad** [comment]
I am on https://login.webmaker.org/account and when I click 'delete my account' nothing happens.

**Comment by cadecairos** [comment]
I was just able to successfully delete my account on login.wm.org/account

Might be a browser/OS thing? I used Firefox 41

**Comment by amirad** [comment]
I think we realized that on some screens it was really hard to see the delete box that popped up (as it is off screen) so people didn't see it at all. 

Either way, the community member didn't respond back with any more issues so will close this.
