### ISSUE TITLE
Makes not deleting

### ISSUE THREAD

**Issue by amirad** [mozilla/login.webmaker.org#345]
Issue with makes deleting. via homeworkmountain@gmail.com

Here is the users issue:
I am having an issue with a webpage. I have erased all my makes but they keep showing up and this is interfering with my actual business. The page in question is https://homeworkmountain.makes.org/thimble/biology_
I already deleted the makes but they are continuing to show. These pages are being indexed by search engines and this is causing SEO issues with my site.

**Comment by jbuck** [comment]
Known issue with makes, we delete the viewable page at https://homeworkmountain.makes.org/thimble/biology but we don't delete the actual content stored on S3 at https://homeworkmountain.makes.org/thimble/biology_ . I've deleted all of the content off of his user account, so he'll be good to go for now.
