### ISSUE TITLE
Password reset emails not received

### ISSUE THREAD

**Issue by matteomenapace** [mozilla/login.webmaker.org#374]
Hello,

I've been using Thimble with a group of 20 adult learners. A few of them couldn't log in, so they did the following:

1. Go to https://id.webmaker.org/reset-password/ 
* Enter email used previously to sign up to Webmaker
* The email check returns positive (so we know they typed in an email address that is linked to an existing Webmaker account) 
* Submit the form
* After submitting the form the page says _We've emailed you instructions for creating a new password._ however no emails were received (not even in the spam folder). 

I tested these steps myself (repeatedly) and got the same result: a new password reset request seems to be successfully created, yet I am not receiving any emails to reset my password.

![reset-password-response](https://cloud.githubusercontent.com/assets/116104/13219150/149a76e0-d966-11e5-8c13-f24e15da5c4f.png)

Something to do with the email delivery system (SQS)? 
https://github.com/mozilla/login.webmaker.org/blob/a4021a7651bf5a1b41b45498843c60f4ba46dd85/app/db/models/index.js#L411

Could you please look into this? Currently I have 4 students who are effectively locked out of their Webmaker account and can't access the Thimble projects they've worked on for 3 weeks. 

Thanks!

cc @jbuck @cadecairos

**Comment by jbuck** [comment]
Matteo: Could you email me and Chris with the email address for the users
in question? jbuck@mozillafoundation.org & cade@mozillafoundation.org

**Comment by cadecairos** [comment]
@matteomenapace Last night some of the hardware that Heroku hosts our Redis instances on had a critical failure, and Heroku moved our instances onto new hosts. Unfortunately, the updates didn't get picked up by our queue processor, and messages started building up.

I've fixed up the issue, and messages have started getting processed. The processor should get through all the messages in the next couple minutes.

**Comment by cadecairos** [comment]
@matteomenapace Looks like the queue has cleared up, and now I'm recieving password reset emails for my own accounts.

Please let us know if your students continue to have issues accessing their accounts.

**Comment by cadecairos** [comment]
It may have processed the requests. However, the secret tokens contained in the emails would have expired by now. They should visit https://thimble.mozilla.org, hit login, and request a new password reset email.

**Comment by matteomenapace** [comment]
Thanks @jbuck  and @cadecairos! I will ask my students to request a new password reset. You can consider this issue closed :)

**Comment by cadecairos** [comment]
Glad we could be of assistance! If you have any more troubles, please let us know.
